apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: system-reserved-infra
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/infra: ""
  kubeletConfig:
    systemReserved:
      cpu: 110m
      memory: 5.26Gi