apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: test argo project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Allow applications to deploy in all namespaces
  destinations:
  - namespace: '*'
    server: '*'
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'