apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-core-project
  namespace: openshift-gitops
spec: {}
# spec:
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   destinations:
#   - namespace: '*'
#     server: '*'
#   sourceRepos:
#   - '*'